"use client";

import {
  ArrowLeft,
  BadgeCheck,
  CalendarClock,
  CreditCard,
  ShieldCheck,
  Sparkles,
  Timer,
  MapPin,
  MessageSquareText,
  Receipt,
  CalendarCheck,
  BellRing,
  Zap,
} from "lucide-react";
import { useMemo, useState } from "react";
import PricingStrip from "@/components/PricingStrip";
import ScanlyUpsellBlock from "@/components/ScanlyUpsellBlock";

type Item = { title: string; price: string; meta?: string; badge?: string };

export default function DemoBooking() {
  const BUSINESS = {
    name: "Glow Aesthetics",
    tagline: "QR deposit flow → less no-shows → cleaner bookings.",
    location: "Winston-Salem, NC",
    hours: "Open today • 9am–6pm",
    inactiveLine:
      "Preview mode • your link stays clean even when checkout is paused (inactive).",
  };

  const deposits: Item[] = useMemo(
    () => [
      { title: "Consult Deposit", price: "$15", meta: "Locks in your spot", badge: "Most used" },
      { title: "Service Deposit", price: "$25", meta: "Applied to total price" },
      { title: "Same-day Hold", price: "$10", meta: "Quick slot reserve" },
      { title: "Late Fee (policy)", price: "$8", meta: "Auto-added if needed" },
    ],
    []
  );

  const quotes = useMemo(
    () => [
      "“People pay the deposit right away. No more back-and-forth.”",
      "“No-shows dropped because it feels official.”",
      "“This is way cleaner than screenshots and DMs.”",
    ],
    []
  );

  const [selected, setSelected] = useState<Item | null>(null);
  const [step, setStep] = useState<"browse" | "confirm" | "success">("browse");

  const openConfirm = (it: Item) => {
    setSelected(it);
    setStep("confirm");
  };

  const reset = () => {
    setSelected(null);
    setStep("browse");
  };

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-6xl px-6 py-6">
        <a
          href="/"
          className="inline-flex items-center gap-2 rounded-2xl border border-white/15 bg-white/5 px-3 py-2 text-sm font-semibold hover:bg-white/10 transition"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Scanly
        </a>

        <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_440px] lg:items-start">
          {/* LEFT: persuasive explanation */}
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/80">
              <BadgeCheck className="h-3.5 w-3.5" />
              Auto-generated by Scanly • booking deposit flow
            </div>

            <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">
              {BUSINESS.name}
            </h1>
            <p className="mt-2 text-white/70">{BUSINESS.tagline}</p>

            <div className="mt-5 grid gap-3 sm:grid-cols-3">
              {[
                { t: "Deposits = commitment", d: "Stops ghosting and no-shows." },
                { t: "One tap clarity", d: "No menus. No confusion." },
                { t: "Feels official", d: "Customers take it seriously." },
              ].map((x) => (
                <div key={x.t} className="rounded-2xl border border-white/10 bg-black/30 p-4">
                  <div className="text-sm font-semibold">{x.t}</div>
                  <div className="mt-1 text-xs text-white/60">{x.d}</div>
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-2xl border border-white/10 bg-black/30 p-4">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <MapPin className="h-4 w-4" />
                {BUSINESS.location}
              </div>
              <div className="mt-1 text-xs text-white/60">{BUSINESS.hours}</div>
            </div>

            <div className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <Sparkles className="h-4 w-4" />
                The “aha” for booking
              </div>
              <div className="mt-2 text-sm text-white/70">
                When someone scans a QR to book, you want them to do one thing:
                <span className="font-semibold text-white"> lock in the appointment.</span>{" "}
                Deposits make booking real — and Scanly makes deposits effortless.
              </div>

              <div className="mt-4 grid gap-2">
                {[
                  "Deposit first → then scheduling feels guaranteed.",
                  "No more “what’s your availability?” ping-pong.",
                  "Optional add-on: SMS reminders cut no-shows even more.",
                ].map((b) => (
                  <div key={b} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm">
                    {b}
                  </div>
                ))}
              </div>

              <div className="mt-4 flex items-center gap-2 text-xs text-white/60">
                <ShieldCheck className="h-4 w-4" />
                {BUSINESS.inactiveLine}
              </div>
            </div>

            {/* ✅ Pricing + your model */}
            <div className="mt-6">
              <PricingStrip
                variantLabel="Booking"
                onChoosePlan={() =>
                  alert("Demo: connect this to your /pricing or Stripe checkout later")
                }
              />
            </div>
          </div>

          {/* RIGHT: phone mini-app */}
          <div className="relative mx-auto w-full max-w-sm">
            <div className="rounded-[34px] border border-white/12 bg-white/5 p-4">
              <div className="mx-auto mb-3 h-1.5 w-16 rounded-full bg-white/10" />

              <div className="overflow-hidden rounded-[26px] border border-white/10 bg-black/70">
                <div className="sticky top-0 z-10 border-b border-white/10 bg-black/70 px-4 py-3 backdrop-blur">
                  <div className="flex items-center justify-between">
                    <div className="text-xs font-semibold text-white/90">{BUSINESS.name}</div>
                    <div className="text-[10px] text-white/55">booking</div>
                  </div>
                  <div className="mt-1 text-[10px] text-white/55">
                    tap • pay deposit • confirm
                  </div>

                  <div className="mt-2 inline-flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-white/70">
                    <Zap className="h-3.5 w-3.5" />
                    Built by Scanly • reduces no-shows
                  </div>
                </div>

                <div className="h-[600px] overflow-y-auto px-4 pb-5 pt-4">
                  <div className="rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs text-white/60">Welcome</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <Timer className="h-3.5 w-3.5" /> fast checkout
                      </div>
                    </div>
                    <div className="mt-1 text-base font-semibold">Lock your appointment</div>
                    <div className="mt-2 text-sm text-white/70">
                      Pay the deposit now — we confirm instantly and send next steps.
                    </div>
                  </div>

                  <div className="mt-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Choose a deposit</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <CreditCard className="h-3.5 w-3.5" /> Apple Pay ready (real builds)
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {deposits.map((it) => (
                        <button
                          key={it.title}
                          onClick={() => openConfirm(it)}
                          className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:bg-white/10 transition active:scale-[0.99]"
                          title="Demo only"
                        >
                          <div className="flex items-center justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <div className="text-sm font-semibold text-white">{it.title}</div>
                                {it.badge && (
                                  <div className="shrink-0 rounded-full border border-white/10 bg-black/35 px-2 py-0.5 text-[10px] text-white/70">
                                    {it.badge}
                                  </div>
                                )}
                              </div>
                              {it.meta && <div className="mt-1 text-xs text-white/60">{it.meta}</div>}
                            </div>
                            <div className="shrink-0 text-sm font-semibold text-white">{it.price}</div>
                          </div>
                          <div className="mt-2 text-[11px] text-white/55">Tap → confirm → pay deposit</div>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Social proof</div>
                      <div className="inline-flex items-center gap-1 text-[11px] text-white/60">
                        <MessageSquareText className="h-3.5 w-3.5" /> verified
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {quotes.map((q) => (
                        <div
                          key={q}
                          className="rounded-2xl border border-white/10 bg-black/35 p-3 text-sm text-white/75"
                        >
                          {q}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-black/40 p-4">
                    <div className="flex items-center gap-2 text-sm font-semibold">
                      <BellRing className="h-4 w-4" /> Add-on that prints money
                    </div>
                    <div className="mt-1 text-sm text-white/70">
                      SMS reminders = fewer no-shows. Scanly sells it as an upgrade.
                    </div>
                    <div className="mt-3 text-[10px] text-white/55">{BUSINESS.inactiveLine}</div>
                  </div>

                  {/* ✅ Your own products (Scanly store) */}
                  <div className="mt-4">
                    <ScanlyUpsellBlock
                      headline="Make your booking feel premium"
                      body="Clients trust what feels official. That’s why Scanly sells QR kits + template packs that look expensive."
                      bullets={[
                        "Deposits + confirmations feel legit",
                        "Optional SMS reminders reduce no-shows",
                        "Custom domain add-on boosts trust",
                      ]}
                    />
                  </div>

                  <div className="mt-4 text-center text-[10px] text-white/45">end of demo • scroll back up</div>
                </div>
              </div>
            </div>

            {/* Confirm / Pay / Success sheet */}
            {selected && (
              <div className="fixed inset-x-0 bottom-0 z-50 px-4 pb-4">
                <div className="mx-auto max-w-sm rounded-3xl border border-white/10 bg-black/85 p-4 backdrop-blur">
                  {step === "confirm" && (
                    <>
                      <div className="text-sm font-semibold">Confirm deposit</div>
                      <div className="mt-1 text-sm text-white/70">
                        {selected.title} • <span className="font-semibold text-white">{selected.price}</span>
                      </div>

                      <div className="mt-3 rounded-2xl border border-white/10 bg-white/5 p-3">
                        <div className="flex items-center gap-2 text-xs text-white/60">
                          <CalendarClock className="h-4 w-4" />
                          Real Scanly flow: pay → confirmation → schedule link
                        </div>
                        <div className="mt-1 text-sm text-white/75">
                          Your client feels “locked in.” That’s the point.
                        </div>
                      </div>

                      <button
                        onClick={() => setStep("success")}
                        className="mt-3 w-full rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Pay deposit (demo)
                      </button>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Cancel
                      </button>

                      <div className="mt-2 text-center text-[10px] text-white/50">{BUSINESS.inactiveLine}</div>
                    </>
                  )}

                  {step === "success" && (
                    <>
                      <div className="text-sm font-semibold">Deposit received ✅</div>
                      <div className="mt-2 grid gap-2">
                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <Receipt className="h-4 w-4" /> Receipt (demo)
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            {selected.title} • {selected.price}
                          </div>
                        </div>

                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <CalendarCheck className="h-4 w-4" /> Next step
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            Real build: redirect to “Pick a time” or auto-confirmed slot.
                          </div>
                        </div>

                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <BellRing className="h-4 w-4" /> Reminder add-on
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            Send an SMS reminder 24h before (upgrade).
                          </div>
                        </div>
                      </div>

                      <a
                        href="/create"
                        className="mt-3 inline-flex w-full items-center justify-center rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Build mine like this
                      </a>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Done
                      </button>
                    </>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
