"use client";

import {
  ArrowLeft,
  BadgeCheck,
  Bolt,
  CreditCard,
  MapPin,
  MessageSquareText,
  ShieldCheck,
  Sparkles,
  Star,
  Timer,
  Scissors,
  Receipt,
  CalendarCheck,
} from "lucide-react";
import { useMemo, useState } from "react";
import PricingStrip from "@/components/PricingStrip";
import ScanlyUpsellBlock from "@/components/ScanlyUpsellBlock";

type Item = { title: string; price: string; meta?: string; badge?: string };

export default function DemoBarber() {
  const BUSINESS = {
    name: "Studio Fade",
    tagline: "QR sign → tap once → you’re booked + paid.",
    location: "Winston-Salem, NC",
    hours: "Open today • 10am–7pm",
    inactiveLine: "Preview mode • checkout pauses when inactive (your link still opens clean).",
  };

  const items: Item[] = useMemo(
    () => [
      { title: "Cut + Lineup", price: "$35", meta: "30 min • walk-ins ok", badge: "Most popular" },
      { title: "Cut + Beard", price: "$50", meta: "45 min • hot towel finish" },
      { title: "Kids Cut", price: "$25", meta: "20 min • ages 5–12" },
      { title: "Edge Up", price: "$15", meta: "10 min • quick clean" },
    ],
    []
  );

  const quotes = useMemo(
    () => [
      "“People scan and instantly know what to tap. No confusion.”",
      "“This replaced ‘DM me’ and cash-app screenshots.”",
      "“Feels like an app when it opens — not a random website.”",
    ],
    []
  );


  const [selected, setSelected] = useState<Item | null>(null);
  const [step, setStep] = useState<"browse" | "confirm" | "success">("browse");
  const [selectedTime, setSelectedTime] = useState<string>("");

  // Demo: generate available slots for today (10am–7pm, 30 min slots)
  const availableSlots = useMemo(() => {
    const slots: string[] = [];
    const startHour = 10;
    const endHour = 19;
    for (let h = startHour; h < endHour; h++) {
      slots.push(`${h}:00`);
      slots.push(`${h}:30`);
    }
    return slots;
  }, []);

  const openConfirm = (it: Item) => {
    setSelected(it);
    setStep("confirm");
    setSelectedTime("");
  };

  const reset = () => {
    setSelected(null);
    setStep("browse");
    setSelectedTime("");
  };

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-6xl px-6 py-6">
        <a
          href="/"
          className="inline-flex items-center gap-2 rounded-2xl border border-white/15 bg-white/5 px-3 py-2 text-sm font-semibold hover:bg-white/10 transition"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Scanly
        </a>

        <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_440px] lg:items-start">
          {/* LEFT: persuasive explanation */}
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/80">
              <BadgeCheck className="h-3.5 w-3.5" />
              Auto-generated by Scanly • ~30 sec setup
            </div>

            <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">
              {BUSINESS.name}
            </h1>
            <p className="mt-2 text-white/70">{BUSINESS.tagline}</p>

            <div className="mt-5 grid gap-3 sm:grid-cols-3">
              {[
                { t: "Built for QR signs", d: "Mirror, chair, door, business card." },
                { t: "Made to convert", d: "One choice → pay → done." },
                { t: "Feels like an app", d: "Not a page of links." },
              ].map((x) => (
                <div key={x.t} className="rounded-2xl border border-white/10 bg-black/30 p-4">
                  <div className="text-sm font-semibold">{x.t}</div>
                  <div className="mt-1 text-xs text-white/60">{x.d}</div>
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-2xl border border-white/10 bg-black/30 p-4">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <MapPin className="h-4 w-4" />
                {BUSINESS.location}
              </div>
              <div className="mt-1 text-xs text-white/60">{BUSINESS.hours}</div>
            </div>

            <div className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <Sparkles className="h-4 w-4" />
                The “aha” for services
              </div>
              <div className="mt-2 text-sm text-white/70">
                People scanning a QR are not in “browse mode.” They’re in “do it now” mode.
                Scanly makes the scan open a mini-app built for one thing:{" "}
                <span className="font-semibold text-white">pick → pay → confirmation.</span>
              </div>

              <div className="mt-4 grid gap-2">
                {[
                  "Replace “DM me” with an instant tap-to-pay flow.",
                  "Stop losing customers to scrolling or decision fatigue.",
                  "Perfect for attention: scan → choose → pay → done.",
                ].map((b) => (
                  <div key={b} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm">
                    {b}
                  </div>
                ))}
              </div>

              <div className="mt-4 flex items-center gap-2 text-xs text-white/60">
                <ShieldCheck className="h-4 w-4" />
                {BUSINESS.inactiveLine}
              </div>
            </div>

            {/* ✅ Pricing + your model */}
            <div className="mt-6">
              <PricingStrip
                variantLabel="Services"
                onChoosePlan={() => alert("Demo: connect this to your /pricing or Stripe checkout later")}
              />
            </div>
          </div>

          {/* RIGHT: phone mini-app */}
          <div className="relative mx-auto w-full max-w-sm">
            <div className="rounded-[34px] border border-white/12 bg-white/5 p-4">
              <div className="mx-auto mb-3 h-1.5 w-16 rounded-full bg-white/10" />

              <div className="overflow-hidden rounded-[26px] border border-white/10 bg-black/70">
                <div className="sticky top-0 z-10 border-b border-white/10 bg-black/70 px-4 py-3 backdrop-blur">
                  <div className="flex items-center justify-between">
                    <div className="text-xs font-semibold text-white/90">{BUSINESS.name}</div>
                    <div className="text-[10px] text-white/55">services</div>
                  </div>
                  <div className="mt-1 text-[10px] text-white/55">tap • confirm • pay</div>

                  <div className="mt-2 inline-flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-white/70">
                    <Bolt className="h-3.5 w-3.5" />
                    Generated by Scanly • built to convert
                  </div>
                </div>

                <div className="h-[600px] overflow-y-auto px-4 pb-5 pt-4">
                  <div className="rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs text-white/60">Welcome</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <Timer className="h-3.5 w-3.5" /> fast flow
                      </div>
                    </div>
                    <div className="mt-1 text-base font-semibold">Pick your service</div>
                    <div className="mt-2 text-sm text-white/70">
                      One screen. One decision. That’s why it works on QR.
                    </div>
                  </div>

                  <div className="mt-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Popular</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <CreditCard className="h-3.5 w-3.5" /> Apple Pay ready (real builds)
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {items.map((it) => (
                        <button
                          key={it.title}
                          onClick={() => openConfirm(it)}
                          className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:bg-white/10 transition active:scale-[0.99]"
                          title="Demo only"
                        >
                          <div className="flex items-center justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <div className="text-sm font-semibold text-white">{it.title}</div>
                                {it.badge && (
                                  <div className="shrink-0 rounded-full border border-white/10 bg-black/35 px-2 py-0.5 text-[10px] text-white/70">
                                    {it.badge}
                                  </div>
                                )}
                              </div>
                              {it.meta && <div className="mt-1 text-xs text-white/60">{it.meta}</div>}
                            </div>
                            <div className="shrink-0 text-sm font-semibold text-white">{it.price}</div>
                          </div>
                          <div className="mt-2 text-[11px] text-white/55">Tap → confirm → pay (demo)</div>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Social proof</div>
                      <div className="inline-flex items-center gap-1 text-[11px] text-white/60">
                        <Star className="h-3.5 w-3.5" /> 5.0
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {quotes.map((q) => (
                        <div key={q} className="rounded-2xl border border-white/10 bg-black/35 p-3 text-sm text-white/75">
                          <div className="flex items-center gap-2 text-[11px] text-white/55">
                            <MessageSquareText className="h-3.5 w-3.5" />
                            Verified scan customer
                          </div>
                          <div className="mt-1">{q}</div>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-black/40 p-4">
                    <div className="flex items-center gap-2 text-sm font-semibold">
                      <Scissors className="h-4 w-4" /> Why this converts
                    </div>
                    <div className="mt-1 text-sm text-white/70">
                      QR shouldn’t open “a website.” It should open the next action.
                    </div>
                    <div className="mt-3 text-[10px] text-white/55">{BUSINESS.inactiveLine}</div>
                  </div>

                  {/* ✅ Your own products (Scanly store) */}
                  <div className="mt-4">
                    <ScanlyUpsellBlock
                      headline="Boost scans → boost sales"
                      body="Want this to look premium in real life? Scanly sells QR kits + high-converting templates so your setup matches the vibe."
                      bullets={[
                        "QR card/sticker kits (mirror/door/vendor-ready)",
                        "Template packs that look expensive",
                        "Add-ons: extra Active QRs, domains, SMS reminders",
                      ]}
                    />
                  </div>

                  <div className="mt-4 text-center text-[10px] text-white/45">end of demo • scroll back up</div>
                </div>
              </div>
            </div>

            {/* Confirm / Pay / Success sheet */}
            {selected && (
              <div className="fixed inset-x-0 bottom-0 z-50 px-4 pb-4">
                <div className="mx-auto max-w-sm rounded-3xl border border-white/10 bg-black/85 p-4 backdrop-blur">
                  {step === "confirm" && (
                    <>
                      <div className="text-sm font-semibold">Confirm service</div>
                      <div className="mt-1 text-sm text-white/70">
                        {selected.title} • <span className="font-semibold text-white">{selected.price}</span>
                      </div>

                      {/* Time slot picker */}
                      <div className="mt-4">
                        <div className="text-xs text-white/80 mb-2">Pick a time slot</div>
                        <div className="grid grid-cols-3 gap-2">
                          {availableSlots.map((slot) => (
                            <button
                              key={slot}
                              type="button"
                              className={`rounded-xl border px-2 py-2 text-xs font-semibold transition ${selectedTime === slot ? "bg-cyan-500/30 border-cyan-500 text-white" : "bg-white/5 border-white/15 text-white/80 hover:bg-cyan-500/10"}`}
                              onClick={() => setSelectedTime(slot)}
                            >
                              {slot}
                            </button>
                          ))}
                        </div>
                        {!selectedTime && (
                          <div className="mt-2 text-xs text-red-400">Please select a time slot.</div>
                        )}
                      </div>

                      <div className="mt-3 rounded-2xl border border-white/10 bg-white/5 p-3">
                        <div className="text-xs text-white/60">What happens on real Scanly</div>
                        <div className="mt-1 text-sm text-white/75">
                          Pay → receipt → confirmation message (and optional booking link).
                        </div>
                      </div>

                      <button
                        onClick={() => selectedTime && setStep("success")}
                        className={`mt-3 w-full rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black transition ${selectedTime ? "hover:bg-white/90" : "opacity-50 cursor-not-allowed"}`}
                        disabled={!selectedTime}
                      >
                        Pay now (demo)
                      </button>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Cancel
                      </button>

                      <div className="mt-2 text-center text-[10px] text-white/50">{BUSINESS.inactiveLine}</div>
                    </>
                  )}

                  {step === "success" && (
                    <>
                      <div className="text-sm font-semibold">Success ✅</div>
                      <div className="mt-2 grid gap-2">
                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <Receipt className="h-4 w-4" /> Receipt (demo)
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            {selected.title} • {selected.price}
                          </div>
                        </div>

                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <CalendarCheck className="h-4 w-4" /> Next step
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            Real builds can add: “Book a time” or “Confirm walk-in.”
                          </div>
                        </div>
                      </div>

                      <a
                        href="/create"
                        className="mt-3 inline-flex w-full items-center justify-center rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Build mine like this
                      </a>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Done
                      </button>
                    </>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
