"use client";

import {
  ArrowLeft,
  BadgeCheck,
  Download,
  CreditCard,
  ShieldCheck,
  Sparkles,
  Timer,
  Receipt,
  Lock,
  Zap,
  FileDown,
  Star,
  MessageSquareText,
} from "lucide-react";
import { useMemo, useState } from "react";
import PricingStrip from "@/components/PricingStrip";
import ScanlyUpsellBlock from "@/components/ScanlyUpsellBlock";

type Item = { title: string; price: string; meta?: string; badge?: string };

export default function DemoDigital() {
  const BRAND = {
    name: "FitDrop",
    tagline: "Scan → pay → instant access. No DMs. No waiting.",
    inactiveLine:
      "Preview mode • your link stays clean even when checkout is paused (inactive).",
  };

  const items: Item[] = useMemo(
    () => [
      { title: "4-Week Training Plan", price: "$19", meta: "Instant download", badge: "Best seller" },
      { title: "Meal Prep Guide", price: "$12", meta: "PDF + grocery list" },
      { title: "Stretch Routine Pack", price: "$8", meta: "Quick recovery flow" },
      { title: "Starter Bundle", price: "$25", meta: "Plan + meals + stretch" },
    ],
    []
  );

  const quotes = useMemo(
    () => [
      "“I paid and got it instantly — that’s the whole point.”",
      "“Way cleaner than sending links through DMs.”",
      "“Feels like a real product, not a random file.”",
    ],
    []
  );

  const [selected, setSelected] = useState<Item | null>(null);
  const [step, setStep] = useState<"browse" | "confirm" | "success">("browse");

  const openConfirm = (it: Item) => {
    setSelected(it);
    setStep("confirm");
  };

  const reset = () => {
    setSelected(null);
    setStep("browse");
  };

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-6xl px-6 py-6">
        <a
          href="/"
          className="inline-flex items-center gap-2 rounded-2xl border border-white/15 bg-white/5 px-3 py-2 text-sm font-semibold hover:bg-white/10 transition"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Scanly
        </a>

        <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_440px] lg:items-start">
          {/* LEFT */}
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/80">
              <BadgeCheck className="h-3.5 w-3.5" />
              Auto-generated by Scanly • digital delivery flow
            </div>

            <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">
              {BRAND.name}
            </h1>
            <p className="mt-2 text-white/70">{BRAND.tagline}</p>

            <div className="mt-5 grid gap-3 sm:grid-cols-3">
              {[
                { t: "Instant access", d: "Pay → unlock → download." },
                { t: "Less support", d: "No “send it again” messages." },
                { t: "Feels premium", d: "Receipt + access screen." },
              ].map((x) => (
                <div key={x.t} className="rounded-2xl border border-white/10 bg-black/30 p-4">
                  <div className="text-sm font-semibold">{x.t}</div>
                  <div className="mt-1 text-xs text-white/60">{x.d}</div>
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <Sparkles className="h-4 w-4" />
                The “aha” for digital products
              </div>
              <div className="mt-2 text-sm text-white/70">
                Scanners are ready to buy *right now*. Scanly turns that moment into:
                <span className="font-semibold text-white"> payment + instant delivery</span>.
              </div>

              <div className="mt-4 grid gap-2">
                {[
                  "Great for TikTok/IG: print one QR and sell everywhere.",
                  "A real receipt makes it feel legitimate (higher trust).",
                  "Access screen reduces refunds + confusion.",
                ].map((b) => (
                  <div key={b} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm">
                    {b}
                  </div>
                ))}
              </div>

              <div className="mt-4 flex items-center gap-2 text-xs text-white/60">
                <ShieldCheck className="h-4 w-4" />
                {BRAND.inactiveLine}
              </div>
            </div>

            {/* ✅ Pricing */}
            <div className="mt-6">
              <PricingStrip
                variantLabel="Digital"
                onChoosePlan={() =>
                  alert("Demo: connect this to your /pricing or Stripe checkout later")
                }
              />
            </div>
          </div>

          {/* RIGHT: phone */}
          <div className="relative mx-auto w-full max-w-sm">
            <div className="rounded-[34px] border border-white/12 bg-white/5 p-4">
              <div className="mx-auto mb-3 h-1.5 w-16 rounded-full bg-white/10" />

              <div className="overflow-hidden rounded-[26px] border border-white/10 bg-black/70">
                <div className="sticky top-0 z-10 border-b border-white/10 bg-black/70 px-4 py-3 backdrop-blur">
                  <div className="flex items-center justify-between">
                    <div className="text-xs font-semibold text-white/90">{BRAND.name}</div>
                    <div className="text-[10px] text-white/55">digital</div>
                  </div>
                  <div className="mt-1 text-[10px] text-white/55">pay • unlock • download</div>

                  <div className="mt-2 inline-flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-white/70">
                    <Zap className="h-3.5 w-3.5" />
                    Built by Scanly • instant delivery
                  </div>
                </div>

                <div className="h-[600px] overflow-y-auto px-4 pb-5 pt-4">
                  <div className="rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs text-white/60">Welcome</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <Timer className="h-3.5 w-3.5" /> fast flow
                      </div>
                    </div>
                    <div className="mt-1 text-base font-semibold">Unlock your download</div>
                    <div className="mt-2 text-sm text-white/70">
                      Pay once → get access instantly. No waiting. No DMs.
                    </div>
                  </div>

                  <div className="mt-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Featured</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <CreditCard className="h-3.5 w-3.5" /> Apple Pay ready (real builds)
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {items.map((it) => (
                        <button
                          key={it.title}
                          onClick={() => openConfirm(it)}
                          className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:bg-white/10 transition active:scale-[0.99]"
                          title="Demo only"
                        >
                          <div className="flex items-center justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <div className="text-sm font-semibold text-white">{it.title}</div>
                                {it.badge && (
                                  <div className="shrink-0 rounded-full border border-white/10 bg-black/35 px-2 py-0.5 text-[10px] text-white/70">
                                    {it.badge}
                                  </div>
                                )}
                              </div>
                              {it.meta && <div className="mt-1 text-xs text-white/60">{it.meta}</div>}
                            </div>
                            <div className="shrink-0 text-sm font-semibold text-white">{it.price}</div>
                          </div>
                          <div className="mt-2 text-[11px] text-white/55">Tap → pay → unlock</div>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Social proof</div>
                      <div className="inline-flex items-center gap-1 text-[11px] text-white/60">
                        <Star className="h-3.5 w-3.5" /> 4.9
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {quotes.map((q) => (
                        <div key={q} className="rounded-2xl border border-white/10 bg-black/35 p-3 text-sm text-white/75">
                          <div className="flex items-center gap-2 text-[11px] text-white/55">
                            <MessageSquareText className="h-3.5 w-3.5" />
                            Verified buyer
                          </div>
                          <div className="mt-1">{q}</div>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-black/40 p-4">
                    <div className="flex items-center gap-2 text-sm font-semibold">
                      <Lock className="h-4 w-4" /> Why this sells
                    </div>
                    <div className="mt-1 text-sm text-white/70">
                      Buyers trust instant delivery + a real receipt. It feels like a product.
                    </div>
                    <div className="mt-3 text-[10px] text-white/55">{BRAND.inactiveLine}</div>
                  </div>

                  {/* ✅ Upsell */}
                  <div className="mt-4">
                    <ScanlyUpsellBlock
                      headline="Turn scans into buyers"
                      body="Want this vibe on your QR? Scanly sells templates + upgrades that make digital products feel premium."
                      bullets={[
                        "Receipt + access screen increases trust",
                        "Template packs make it look expensive",
                        "Add-ons: custom domain, advanced analytics, more active QRs",
                      ]}
                    />
                  </div>

                  <div className="mt-4 text-center text-[10px] text-white/45">end of demo • scroll back up</div>
                </div>
              </div>
            </div>

            {/* Bottom sheet */}
            {selected && (
              <div className="fixed inset-x-0 bottom-0 z-50 px-4 pb-4">
                <div className="mx-auto max-w-sm rounded-3xl border border-white/10 bg-black/85 p-4 backdrop-blur">
                  {step === "confirm" && (
                    <>
                      <div className="text-sm font-semibold">Unlock download</div>
                      <div className="mt-1 text-sm text-white/70">
                        {selected.title} • <span className="font-semibold text-white">{selected.price}</span>
                      </div>

                      <div className="mt-3 rounded-2xl border border-white/10 bg-white/5 p-3">
                        <div className="flex items-center gap-2 text-xs text-white/60">
                          <Download className="h-4 w-4" />
                          Real Scanly: pay → receipt → access screen → download link
                        </div>
                        <div className="mt-1 text-sm text-white/75">
                          No “check your email” confusion. Instant.
                        </div>
                      </div>

                      <button
                        onClick={() => setStep("success")}
                        className="mt-3 w-full rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Pay & unlock (demo)
                      </button>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Cancel
                      </button>

                      <div className="mt-2 text-center text-[10px] text-white/50">{BRAND.inactiveLine}</div>
                    </>
                  )}

                  {step === "success" && (
                    <>
                      <div className="text-sm font-semibold">Unlocked ✅</div>
                      <div className="mt-2 grid gap-2">
                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <Receipt className="h-4 w-4" /> Receipt (demo)
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            {selected.title} • {selected.price}
                          </div>
                        </div>

                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <FileDown className="h-4 w-4" /> Access granted
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            Real build: show a download button + a backup link.
                          </div>
                        </div>
                      </div>

                      <a
                        href="/create"
                        className="mt-3 inline-flex w-full items-center justify-center rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Build mine like this
                      </a>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Done
                      </button>
                    </>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
