"use client";

import {
  ArrowLeft,
  BadgeCheck,
  CreditCard,
  ShieldCheck,
  Sparkles,
  Timer,
  Receipt,
  ShoppingBag,
  Truck,
  Star,
  MessageSquareText,
  Zap,
  PackageCheck,
} from "lucide-react";
import { useMemo, useState } from "react";
import PricingStrip from "@/components/PricingStrip";
import ScanlyUpsellBlock from "@/components/ScanlyUpsellBlock";

type Item = { title: string; price: string; meta?: string; badge?: string };

export default function DemoProducts() {
  const SHOP = {
    name: "Pop-Up Supply",
    tagline: "QR shop for real life: vendor tables, flyers, bags, and events.",
    inactiveLine:
      "Preview mode • your link stays clean even when checkout is paused (inactive).",
  };

  const items: Item[] = useMemo(
    () => [
      { title: "Logo Tee", price: "$25", meta: "Sizes S–XL", badge: "Top seller" },
      { title: "Sticker Pack", price: "$7", meta: "10 stickers • waterproof" },
      { title: "Hoodie", price: "$45", meta: "Heavyweight" },
      { title: "Bundle: Tee + Stickers", price: "$29", meta: "Best value" },
    ],
    []
  );

  const quotes = useMemo(
    () => [
      "“People scanned the table sign and checked out right there.”",
      "“This beats typing a long URL or telling people ‘DM me’.”",
      "“It feels like a real checkout flow — not a link list.”",
    ],
    []
  );

  const [selected, setSelected] = useState<Item | null>(null);
  const [step, setStep] = useState<"browse" | "confirm" | "success">("browse");

  const openConfirm = (it: Item) => {
    setSelected(it);
    setStep("confirm");
  };

  const reset = () => {
    setSelected(null);
    setStep("browse");
  };

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-6xl px-6 py-6">
        <a
          href="/"
          className="inline-flex items-center gap-2 rounded-2xl border border-white/15 bg-white/5 px-3 py-2 text-sm font-semibold hover:bg-white/10 transition"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Scanly
        </a>

        <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_440px] lg:items-start">
          {/* LEFT */}
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/80">
              <BadgeCheck className="h-3.5 w-3.5" />
              Auto-generated by Scanly • product list + checkout flow
            </div>

            <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">
              {SHOP.name}
            </h1>
            <p className="mt-2 text-white/70">{SHOP.tagline}</p>

            <div className="mt-5 grid gap-3 sm:grid-cols-3">
              {[
                { t: "Perfect for events", d: "QR sign = instant checkout." },
                { t: "Short list sells", d: "A few items convert better." },
                { t: "Premium trust", d: "Receipt + confirmation." },
              ].map((x) => (
                <div key={x.t} className="rounded-2xl border border-white/10 bg-black/30 p-4">
                  <div className="text-sm font-semibold">{x.t}</div>
                  <div className="mt-1 text-xs text-white/60">{x.d}</div>
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <Sparkles className="h-4 w-4" />
                The “aha” for physical products
              </div>
              <div className="mt-2 text-sm text-white/70">
                People at a table/event don’t want to scroll 50 items. Scanly builds a tight,
                high-converting mini-shop:
                <span className="font-semibold text-white"> browse → pick → pay → done.</span>
              </div>

              <div className="mt-4 grid gap-2">
                {[
                  "Ideal for pop-ups: one QR handles the line.",
                  "Short lists + bundles increase average order.",
                  "Add-on: multiple active QRs for different locations/campaigns.",
                ].map((b) => (
                  <div key={b} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm">
                    {b}
                  </div>
                ))}
              </div>

              <div className="mt-4 flex items-center gap-2 text-xs text-white/60">
                <ShieldCheck className="h-4 w-4" />
                {SHOP.inactiveLine}
              </div>
            </div>

            {/* ✅ Pricing */}
            <div className="mt-6">
              <PricingStrip
                variantLabel="Products"
                onChoosePlan={() =>
                  alert("Demo: connect this to your /pricing or Stripe checkout later")
                }
              />
            </div>
          </div>

          {/* RIGHT: phone */}
          <div className="relative mx-auto w-full max-w-sm">
            <div className="rounded-[34px] border border-white/12 bg-white/5 p-4">
              <div className="mx-auto mb-3 h-1.5 w-16 rounded-full bg-white/10" />

              <div className="overflow-hidden rounded-[26px] border border-white/10 bg-black/70">
                <div className="sticky top-0 z-10 border-b border-white/10 bg-black/70 px-4 py-3 backdrop-blur">
                  <div className="flex items-center justify-between">
                    <div className="text-xs font-semibold text-white/90">{SHOP.name}</div>
                    <div className="text-[10px] text-white/55">products</div>
                  </div>
                  <div className="mt-1 text-[10px] text-white/55">tap • pay • confirmation</div>

                  <div className="mt-2 inline-flex items-center justify-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-white/70">
                    <Zap className="h-3.5 w-3.5" />
                    Built by Scanly • made for pop-ups
                  </div>
                </div>

                <div className="h-[600px] overflow-y-auto px-4 pb-5 pt-4">
                  <div className="rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs text-white/60">Welcome</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <Timer className="h-3.5 w-3.5" /> quick checkout
                      </div>
                    </div>
                    <div className="mt-1 text-base font-semibold">Grab something fast</div>
                    <div className="mt-2 text-sm text-white/70">
                      Short list on purpose — it converts better at events.
                    </div>
                  </div>

                  <div className="mt-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Featured</div>
                      <div className="inline-flex items-center gap-1 text-[10px] text-white/55">
                        <CreditCard className="h-3.5 w-3.5" /> Apple Pay ready (real builds)
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {items.map((it) => (
                        <button
                          key={it.title}
                          onClick={() => openConfirm(it)}
                          className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:bg-white/10 transition active:scale-[0.99]"
                          title="Demo only"
                        >
                          <div className="flex items-center justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <div className="text-sm font-semibold text-white">{it.title}</div>
                                {it.badge && (
                                  <div className="shrink-0 rounded-full border border-white/10 bg-black/35 px-2 py-0.5 text-[10px] text-white/70">
                                    {it.badge}
                                  </div>
                                )}
                              </div>
                              {it.meta && <div className="mt-1 text-xs text-white/60">{it.meta}</div>}
                            </div>
                            <div className="shrink-0 text-sm font-semibold text-white">{it.price}</div>
                          </div>
                          <div className="mt-2 text-[11px] text-white/55">Tap → pay → receipt</div>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-white/5 p-4">
                    <div className="flex items-center justify-between">
                      <div className="text-xs font-semibold text-white/60">Social proof</div>
                      <div className="inline-flex items-center gap-1 text-[11px] text-white/60">
                        <Star className="h-3.5 w-3.5" /> 4.8
                      </div>
                    </div>

                    <div className="mt-2 grid gap-2">
                      {quotes.map((q) => (
                        <div key={q} className="rounded-2xl border border-white/10 bg-black/35 p-3 text-sm text-white/75">
                          <div className="flex items-center gap-2 text-[11px] text-white/55">
                            <MessageSquareText className="h-3.5 w-3.5" />
                            Verified buyer
                          </div>
                          <div className="mt-1">{q}</div>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="mt-4 rounded-3xl border border-white/10 bg-black/40 p-4">
                    <div className="flex items-center gap-2 text-sm font-semibold">
                      <ShoppingBag className="h-4 w-4" /> Why it works
                    </div>
                    <div className="mt-1 text-sm text-white/70">
                      People scanning at a table want a clean yes/no decision — not a catalog.
                    </div>
                    <div className="mt-3 text-[10px] text-white/55">{SHOP.inactiveLine}</div>
                  </div>

                  {/* ✅ Upsell */}
                  <div className="mt-4">
                    <ScanlyUpsellBlock
                      headline="Make your QR table sign look expensive"
                      body="Scanly sells QR sign kits + templates so your setup looks premium and converts better."
                      bullets={[
                        "QR stickers + mini signs for vendor tables",
                        "Template packs built for pop-ups",
                        "Add-ons: extra active QRs for different campaigns/locations",
                      ]}
                    />
                  </div>

                  <div className="mt-4 text-center text-[10px] text-white/45">end of demo • scroll back up</div>
                </div>
              </div>
            </div>

            {/* Bottom sheet */}
            {selected && (
              <div className="fixed inset-x-0 bottom-0 z-50 px-4 pb-4">
                <div className="mx-auto max-w-sm rounded-3xl border border-white/10 bg-black/85 p-4 backdrop-blur">
                  {step === "confirm" && (
                    <>
                      <div className="text-sm font-semibold">Confirm order</div>
                      <div className="mt-1 text-sm text-white/70">
                        {selected.title} • <span className="font-semibold text-white">{selected.price}</span>
                      </div>

                      <div className="mt-3 rounded-2xl border border-white/10 bg-white/5 p-3">
                        <div className="flex items-center gap-2 text-xs text-white/60">
                          <PackageCheck className="h-4 w-4" />
                          Real Scanly: pay → receipt → confirmation → fulfillment step
                        </div>
                        <div className="mt-1 text-sm text-white/75">
                          Looks legit. Buyer trusts it.
                        </div>
                      </div>

                      <button
                        onClick={() => setStep("success")}
                        className="mt-3 w-full rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Pay now (demo)
                      </button>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Cancel
                      </button>

                      <div className="mt-2 text-center text-[10px] text-white/50">{SHOP.inactiveLine}</div>
                    </>
                  )}

                  {step === "success" && (
                    <>
                      <div className="text-sm font-semibold">Order confirmed ✅</div>
                      <div className="mt-2 grid gap-2">
                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <Receipt className="h-4 w-4" /> Receipt (demo)
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            {selected.title} • {selected.price}
                          </div>
                        </div>

                        <div className="rounded-2xl border border-white/10 bg-white/5 p-3">
                          <div className="flex items-center gap-2 text-sm font-semibold">
                            <Truck className="h-4 w-4" /> Fulfillment step
                          </div>
                          <div className="mt-1 text-sm text-white/70">
                            Real build: “Pickup now” or “Shipping info” screen.
                          </div>
                        </div>
                      </div>

                      <a
                        href="/create"
                        className="mt-3 inline-flex w-full items-center justify-center rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90 transition"
                      >
                        Build mine like this
                      </a>

                      <button
                        onClick={reset}
                        className="mt-2 w-full rounded-2xl border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold hover:bg-white/10 transition"
                      >
                        Done
                      </button>
                    </>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
